---
name: openweather
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  chopper: ^3.0.3
  sembast: ^2.4.7+4
  chopper_generator: ^3.0.5
  build_runner: ^1.10.0
  path_provider: ^1.6.11
  get_it: ^4.0.4
  throttling: ^0.8.0
  google_fonts: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
